import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProductProvider from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Burguer-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ProductProvider />
      </body>
    </html>
  );
}
